/**
 * Content Type Definitions for Garage Cowboy Website
 * Used with useContent hook to load JSON data files
 */

// =============================================================================
// SHARED INTERFACES
// =============================================================================

export interface Hero {
  headline: string;
  subheadline: string;
  backgroundImage: string;
  ctaText: string;
  ctaLink?: string;
}

export interface CTA {
  title: string;
  subtitle?: string;
  buttonText: string;
  buttonLink?: string;
  phone?: string;
}

// New interfaces for docx-parsed content
export interface ContentSection {
  title: string;
  content: string;
}

export interface FAQ {
  question: string;
  answer: string;
}

export interface DocxContent {
  title: string;
  intro: string;
}

// =============================================================================
// MARKDOWN-FIRST CONTENT (from parsed .md files)
// =============================================================================

/**
 * Base interface for all markdown-first content
 * Generated by parse-md.js from Webzite Copy .md files
 */
export interface MarkdownContent {
  title: string;
  intro: string;
  sections: ContentSection[];
  faqs: FAQ[];
}

export interface Testimonial {
  quote: string;
  author: string;
  location?: string;
  rating?: number;
}

// =============================================================================
// ABOUT US PAGE
// =============================================================================

export interface CoreValue {
  icon: string;
  title: string;
  description: string;
}

export interface TeamMember {
  photo: string;
  name: string;
  role: string;
  bio?: string;
}

export interface AboutUsContent {
  hero: Hero;
  companyStory: {
    title: string;
    text: string;
    image: string;
    founded: string;
  };
  coreValues: CoreValue[];
  teamMembers: TeamMember[];
  certifications: string[];
  cta: CTA;
  // Extended from docx
  docxContent?: DocxContent;
  sections?: ContentSection[];
  faqs?: FAQ[];
}

// =============================================================================
// SERVICES PAGE
// =============================================================================

export interface Service {
  id: string;
  category: string;
  title: string;
  description: string;
  image: string;
  pricing?: string;
  features: string[];
}

export interface ProcessStep {
  step: number;
  title: string;
  description: string;
  icon?: string;
}

export interface ServicesPageContent {
  hero: Hero;
  categories: string[];
  services: Service[];
  processSteps: ProcessStep[];
  warranty: {
    title: string;
    description: string;
    years: number;
  };
  cta: CTA;
  // Extended from docx
  docxContent?: DocxContent;
  sections?: ContentSection[];
  faqs?: FAQ[];
}

// =============================================================================
// TEXAS PAGE
// =============================================================================

export interface CityService {
  name: string;
  slug: string;
  services: string[];
  phone?: string;
}

export interface CoverageStats {
  cities: number;
  counties: number;
  yearsServing: number;
}

export interface TexasPageContent {
  hero: Hero;
  coverageStats: CoverageStats;
  cities: CityService[];
  map: {
    embedUrl: string;
    title: string;
  };
  testimonials: Testimonial[];
  cta: CTA;
  // Extended from docx
  docxContent?: DocxContent;
  sections?: ContentSection[];
  faqs?: FAQ[];
}

// =============================================================================
// RESIDENTIAL PAGE
// =============================================================================

export interface Benefit {
  icon: string;
  title: string;
  description: string;
}

export interface BeforeAfter {
  problem: string;
  solution: string;
  beforeImage: string;
  afterImage: string;
}

export interface ResidentialService {
  title: string;
  description: string;
  image: string;
  features: string[];
}

export interface ResidentialPageContent {
  hero: Hero;
  benefits: Benefit[];
  services: ResidentialService[];
  beforeAfterGallery: BeforeAfter[];
  maintenanceTips: string[];
  warranty: {
    title: string;
    description: string;
  };
  cta: CTA;
  // Extended from docx
  docxContent?: DocxContent;
  sections?: ContentSection[];
  faqs?: FAQ[];
}

// =============================================================================
// COMMERCIAL PAGE
// =============================================================================

export interface CaseStudy {
  title: string;
  industry: string;
  challenge: string;
  solution: string;
  result: string;
  image?: string;
}

export interface PricingPlan {
  name: string;
  price: string;
  period: string;
  features: string[];
  isFeatured: boolean;
  ctaText: string;
}

export interface CommercialService {
  title: string;
  description: string;
  icon: string;
}

export interface CommercialPageContent {
  hero: Hero;
  stats: {
    clients: number;
    years: number;
    projects: number;
  };
  industries: string[];
  services: CommercialService[];
  reasons: string[];
  caseStudies: CaseStudy[];
  plans: PricingPlan[];
  certifications: string[];
  cta: CTA;
  // Extended from docx
  docxContent?: DocxContent;
  sections?: ContentSection[];
  faqs?: FAQ[];
}

// =============================================================================
// SERVICE DETAIL PAGE (for /services/:slug routes)
// =============================================================================

export interface ServiceDetailContent {
  slug: string;
  title: string;
  intro: string;
  hero: {
    headline: string;
    subheadline: string;
    ctaText: string;
    ctaLink: string;
  };
  sections: ContentSection[];
  faqs: FAQ[];
  cta: CTA;
}

// =============================================================================
// CITY PAGE (for Texas city anchors)
// =============================================================================

export interface CityContent {
  slug: string;
  name: string;
  title: string;
  intro: string;
  sections: ContentSection[];
  faqs: FAQ[];
  services: string[];
  phone: string;
}

// =============================================================================
// UNION TYPE FOR ALL PAGE CONTENT
// =============================================================================

export type PageContent =
  | AboutUsContent
  | ServicesPageContent
  | TexasPageContent
  | ResidentialPageContent
  | CommercialPageContent
  | ServiceDetailContent
  | CityContent;

